# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParametersWindpw(object):
    def setupUi(self, ParametersWindpw):
        ParametersWindpw.setObjectName("ParametersWindpw")
        ParametersWindpw.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(ParametersWindpw)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.0753518, y1:0.08, x2:1, y2:1, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(0, 255, 255, 255));}")
        self.centralwidget.setObjectName("centralwidget")
        self.TitreFenetre = QtWidgets.QLabel(self.centralwidget)
        self.TitreFenetre.setGeometry(QtCore.QRect(225, 10, 911, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(55)
        self.TitreFenetre.setFont(font)
        self.TitreFenetre.setObjectName("TitreFenetre")
        self.ApiKeyTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.ApiKeyTextBox.setGeometry(QtCore.QRect(360, 120, 231, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setWeight(50)
        self.ApiKeyTextBox.setFont(font)
        self.ApiKeyTextBox.setObjectName("ApiKeyTextBox")
        self.BulbLabelTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.BulbLabelTextBox.setGeometry(QtCore.QRect(360, 270, 231, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(False)
        font.setWeight(50)
        self.BulbLabelTextBox.setFont(font)
        self.BulbLabelTextBox.setObjectName("BulbLabelTextBox")
        fontButtons = QtGui.QFont()
        fontButtons.setFamily("Arial Black")
        fontButtons.setPointSize(10)
        self.BoutonApiKey = QtWidgets.QPushButton(self.centralwidget)
        self.BoutonApiKey.setGeometry(QtCore.QRect(430, 170, 100, 40))
        self.BoutonApiKey.setObjectName("BoutonApiKey")
        self.BoutonApiKey.setFont(fontButtons)
        self.BoutonBulbLabel = QtWidgets.QPushButton(self.centralwidget)
        self.BoutonBulbLabel.setGeometry(QtCore.QRect(430, 320, 100, 40))
        self.BoutonBulbLabel.setObjectName("BoutonBulbLabel")
        self.BoutonBulbLabel.setFont(fontButtons)
        self.BoutonRetourMenu = QtWidgets.QPushButton(self.centralwidget)
        self.BoutonRetourMenu.setGeometry(QtCore.QRect(430, 450, 100, 40))
        self.BoutonRetourMenu.setObjectName("BoutonRetourMenu")
        self.BoutonRetourMenu.setFont(fontButtons)
        self.Instructions = QtWidgets.QLabel(self.centralwidget)
        self.Instructions.setGeometry(QtCore.QRect(110, 360, 721, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.Instructions.setFont(font)
        self.Instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.Instructions.setWordWrap(True)
        self.Instructions.setObjectName("Instructions")
        ParametersWindpw.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParametersWindpw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        ParametersWindpw.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParametersWindpw)
        self.statusbar.setObjectName("statusbar")
        ParametersWindpw.setStatusBar(self.statusbar)

        self.retranslateUi(ParametersWindpw)
        QtCore.QMetaObject.connectSlotsByName(ParametersWindpw)

    def retranslateUi(self, ParametersWindpw):
        _translate = QtCore.QCoreApplication.translate
        ParametersWindpw.setWindowTitle(_translate("ParametersWindpw", "MainWindow"))
        self.TitreFenetre.setText(_translate("ParametersWindpw", "Paramètres"))
        self.ApiKeyTextBox.setPlaceholderText(_translate("ParametersWindpw", "LIFX API Key"))
        self.BulbLabelTextBox.setPlaceholderText(_translate("ParametersWindpw", "LIFX Bulb Label"))
        self.BoutonApiKey.setText(_translate("ParametersWindpw", "Soumettre"))
        self.BoutonBulbLabel.setText(_translate("ParametersWindpw", "Soumettre"))
        self.BoutonRetourMenu.setText(_translate("ParametersWindpw", "Retour"))
        self.Instructions.setText(_translate("ParametersWindpw", "Si vous ne savez pas comment générer votre LIFX API Key, veuillez vous référer au site web suivant: https://community.lifx.com/t/creating-a-lifx-http-api-token/25 "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ParametersWindpw = QtWidgets.QMainWindow()
    ui = Ui_ParametersWindpw()
    ui.setupUi(ParametersWindpw)
    ParametersWindpw.show()
    sys.exit(app.exec_())
